steps:
  # Langkah 1: Membangun image Docker
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "asia.gcr.io/ide-kita/backend-idekita:1.0", "."]

  # Langkah 2: Mengunggah image Docker ke Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "asia.gcr.io/ide-kita/backend-idekita:1.0"]
    
  # Langkah tambahan: Menampilkan isi direktori /app
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        ls -la /
    
  # Langkah 3: Menerbitkan aplikasi ke Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "backend"
      - "--image"
      - "asia.gcr.io/ide-kita/backend-idekita:1.0"
      - "--platform"
      - "managed"
      - "--region"
      - "asia-southeast2"
      - "--allow-unauthenticated"
      - "--port"
      - "8000"
